# -*- coding: utf-8 -*-
"""secrecy_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P1etAPJRJ2MjQhgrJRX_mzwsj0LoRUEh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import subprocess

with open('tcp_timing.txt', 'r') as f:
    lines = (line.strip() for line in f if line)
    TCP_data = [float(line) for line in lines]

with open('mpi_timing.txt', 'r') as f:
    lines = (line.strip() for line in f if line)
    TCP_data = [float(line) for line in lines]

print(MPI_data, TCP_data)

num_elements = [1024, 4096, 16384, 65536, 262144, 1048576]

plt.plot(num_elements, MPI_data, label='MPI')
plt.plot(num_elements,TCP_data, label='TCP')
plt.legend()

plt.savefig("timingplot.png")